#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color "#4a91e8"
bspc config presel_feedback_color "#9AC2F2"
bspc config focus_follows_pointer true
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config automatic_scheme     spiral
bspc config initial_polarity     first_child

bspc rule -a Brave-browser desktop='^1'

polybar &
picom &
feh --bg-fill ~/Pictures/Wallpapers/matt-palmer-M7EnqaUt6Yg-unsplash.jpg &
greenclip daemon &
# lxpolkit &
unclutter &

xsetroot -cursor_name left_ptr &
